steps:
  - label: 'pwd'
    command: pwd
    
  - label: 'git remote branches branch'
    command: git branch -r
    
  - label: 'git reflog'
    command: git reflog
    
  - label: ':playground: touch it'
    command: touch /tmp/buildkite
