steps:
  - label: "merge master branch"
    command:
      - echo git 
      - echo git merge master
    branches: "feature/*"
  
  - wait: ~
    continue_on_failure: true
  
  - label: 'pwd'
    command: pwd
    
  - trigger: sandbox
    label: "Feature Branche Trigger"
    build:
      message: "$BUILDKITE_BRANCH branch trigger"
      branch: "feature/bigone"
    async: true   
    branches: "master"
      
  - label: "update master branch"
    command: 
      - echo git checkout master
      - echo git merge $BUILDKITE_BRANCH
      - echo git push origin master
    branches: "feature/*"
