steps:
  - label: ':playground: pwd'
    command: pwd
    
  - label: ':playground: git branches'
    command: git branch
    
  - label: ':playground: git branches'
    command: git reflog
    
  - label: ':playground: touch it'
    command: touch /tmp/buildkite
