steps:
  - label: 'pwd'
    command: pwd
    
  - label: 'branch updater'
    command: | 
              for branch in $(git ls-remote --heads origin | sed 's|^.*refs/heads/||'); do 
                echo $branch
              done
